services:
  bench:
    image: nvcr.io/nvidia/pytorch:23.04-py3
    working_dir: /workspace/
    volumes:
      - ./:/workspace
    shm_size: '8gb'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

    command: bash run.sh